local module = {
    alarm = {
      desc = "The start event. Should always be present in all maps."
    }
    scp008 = {
      desc = "The event in SCP-008's chamber where SCP-173 breaks the window. Should always be present in all maps."
    }
    scp914 = {
      desc = "SCP-914's mechanism event. Required for SCP-914 to function."
    }
    coffin = {
      desc = "SCP-895's chamber event."
    }
    coffin106 = {
      desc = "SCP-895's chamber event + SCP-106 spawn near the coffin."
    }
return module
