local dispense0 = game.ServerStorage.SFX.SCP.294.dispense0

local module = {
	AIR = {
		color = Color3.fromRGB(0, 0, 0),
		alpha = 0,
		refusemessage = "There is nothing to drink in the cup",
		dispensesound = dispense0
	},
	NOTHING = {
		color = Color3.fromRGB(0, 0, 0),
		alpha = 0,
		refusemessage = "There is nothing to drink in the cup",
		dispensesound = dispense0
	},
	CUP = {
		color = Color3.fromRGB(0, 0, 0),
		alpha = 0,
		refusemessage = "There is nothing to drink in the cup",
		dispensesound = dispense0
	},
	EMPTINESS = {
		color = Color3.fromRGB(0, 0, 0),
		alpha = 0,
		refusemessage = "There is nothing to drink in the cup",
		dispensesound = dispense0
	},
	VACUUM = {
		color = Color3.fromRGB(0, 0, 0),
		alpha = 0,
		refusemessage = "There is nothing to drink in the cup",
		dispensesound = dispense0
	},
	HL3 = {
		color = Color3.fromRGB(0, 0, 0),
		alpha = 0,
		refusemessage = "There is nothing to drink in the cup",
		dispensesound = dispense0
	},
	["HALF LIFE 3"] = {
		color = Color3.fromRGB(0, 0, 0),
		alpha = 0,
		refusemessage = "There is nothing to drink in the cup",
		dispensesound = dispense0
	},

	ALCOHOL = {
		color = Color3.fromRGB(255, 255, 255),
		alpha = 0.5,
		sound = ahh,
		dispensesound = dispense1,
		message = "Damn, that's strong."
	},
	ETHANOL = {
		color = Color3.fromRGB(255, 255, 255),
		alpha = 0.5,
		sound = ahh,
		dispensesound = dispense1,
		message = "Damn, that's strong."
	},
	["ETHANOL LIQUID"] = {
		color = Color3.fromRGB(255, 255, 255),
		alpha = 0.5,
		sound = ahh,
		dispensesound = dispense1,
		message = "Damn, that's strong."
	},
	SPIRIT = {
		color = Color3.fromRGB(255, 255, 255),
		alpha = 0.5,
		sound = ahh,
		dispensesound = dispense1,
		message = "Damn, that's strong."
	},
	VODKA = {
		color = Color3.fromRGB(255, 255, 255),
		alpha = 0.5,
		sound = ahh,
		dispensesound = dispense1,
		message = "Damn, that's strong."
	},
	[["ALOE VERA DRINK"]] = {
		color = Color3.fromRGB(217, 214, 186),
		alpha = 0.8,
		sound = ahh,
		dispensesound = dispense1,
		damage = -0.2
	}
}
return module
